service: BlueRetro

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-west-2'}
  environment:
      tableName:
        Ref: BlueRetroTable

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ BlueRetroTable, Arn ]

custom:
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:provider.stage}, self:custom.tableThroughputs.default}

resources:
  - ${file(serverless/resources/dynamodb-table.yml)}
  - ${file(serverless/resources/cognito-user-pool.yml)}
  - ${file(serverless/resources/cognito-identity-pool.yml)}
