// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const aws = {
  Auth: {
    mandatorySignIn: true,
    region: 'us-west-2',
    userPoolId: 'us-west-2_9mFjGvgx7',
    identityPoolId: 'us-west-2:1bf6b6f6-0037-4cfa-a77c-be1fa4e697e1',
    userPoolWebClientId: '74q6b9m1i7t6gct4har1fovr21'
  }
}

export default aws
